import { defineConfig } from 'vite'
import tailwindcss from '@tailwindcss/vite'
import { resolve } from 'node:path'
import { globSync } from 'node:fs'

// Static multi-page marketing site, deployed to GitHub Pages on the
// nectardocs.com apex (custom domain → base '/'). Each top-level page is a
// separate HTML entry so Vite emits clean /tos and /privacy outputs.
//
// Release pages under releases/ are GENERATED by scripts/build-releases.mjs
// (see the predev/prebuild hooks) and picked up here by glob. Vite emits an HTML
// entry at its path relative to root regardless of the input key, so
// releases/0.6.0/index.html lands at dist/releases/0.6.0/index.html.
const releasePages = Object.fromEntries(
  globSync('releases/**/index.html', { cwd: import.meta.dirname }).map((p) => [
    p.replace(/\/index\.html$/, '').replace(/\//g, '-'),
    resolve(import.meta.dirname, p),
  ]),
)

export default defineConfig({
  plugins: [tailwindcss()],
  build: {
    rollupOptions: {
      input: {
        index: resolve(import.meta.dirname, 'index.html'),
        download: resolve(import.meta.dirname, 'download.html'),
        tos: resolve(import.meta.dirname, 'tos.html'),
        privacy: resolve(import.meta.dirname, 'privacy.html'),
        ...releasePages,
      },
    },
  },
})
